#! /bin/sh
# /etc/init.d/estop

### BEGIN INIT INFO
# Provides:          estop
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop Crazyflie estop util
# Description:       Start and stop Crazyflie estop util
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting estop"
    /usr/bin/sudo -u pi python3 /home/pi/icra-2017-demos/estop-button/estop.py > /tmp/estop.log 2>&1 &
    ;;
  stop)
    echo "Stopping estop"
    killall python3
    ;;
  *)
    echo "Usage: /etc/init.d/estop {start|stop}"
    exit 1
    ;;
esac

exit 0
